#!/bin/bash

if [ ! -d /data/app ]
then
  echo "App. volume mount is required."
  exit 1
fi

if [ -f /data/app/requirements.txt ]
then
  echo "PIP Requirements installing .."
  dp-pip install -r /data/app/requirements.txt > /dev/null 2>&1

  if [ $? -eq 0 ]
  then
    echo "PIP Requirements installed."
  else
    echo "PIP Requirements installing failed."
    return
  fi
fi

netstat -nr | grep '^0\.0\.0\.0' | awk '{print $2}' > /data/dp/host_addr
export host_addr=$(cat /data/dp/host_addr)

if [ "$(cat /etc/hosts | grep host.addr)" = "" ]
then
  echo "$host_addr host.addr" >> /etc/hosts
fi

if [ -f /data/before ]
then
  bash /data/before
fi

cd /data/app
dp4p run --mode=production --port=$(cat /data/dp/port) > /data/out.log 2>&1 &

