#!/bin/bash

account="why2pac"
ver="0.3"

for pyver in py27 py34 py35 pypy27; do
  sudo docker rmi $account/dp4p:base-$pyver-$ver
  sudo docker rmi $account/dp4p:base-$pyver

  bash build_docker $pyver dp4p/base-$pyver-$ver
  bash build_docker $pyver $account/dp4p:base-$pyver-$ver
  #bash build_docker $pyver $account/dp4p:base-$pyver

  if [ "$(sudo docker images | grep $account/dp4p | grep base-$pyver)" = "" ]
  then
    echo "Failed to build a dockerfile. ($pyver)"
    exit 1
  fi
done

for pyver in py27 py34 py35 pypy27; do
  sudo docker push $account/dp4p:base-$pyver-$ver
  #sudo docker push $account/dp4p:base-$pyver
done
