#!/bin/bash

pyver=$1

if [ "$pyver" = "" ]
then
  echo "usage: run py_version[py27|py34|py35|pypy27]"
  return
fi

sudo docker run -it -p 8888:52848 -v "$(dirname $(dirname $(pwd)))/example:/data/app" dp4p:base-$pyver bash
