#!/bin/bash

pyver=$1

if [ "$pyver" = "" ]
then
  echo "usage: run py_version[py27|py34|py35|pypy27]"
  return
fi

if [ ! -f ./python/$pyver ]
then
  echo "The specified python version ($pyver) is invalid or not supported."
  return
fi

sudo docker run -it dp4p:core-$pyver bash
