#!/usr/bin/env python

import os

version_py = os.path.join(os.getcwd(), '../../dp_tornado/version.py')

with file(version_py, 'r') as fp:
    for c in fp.read().split('\n'):
        exec(c)

print(__version__)
