#!/bin/bash

pyver=$1
dpver=$(./dpver)

if [ "$pyver" = "" ]
then
  echo "usage: run py_version[py27|py34|py35|pypy27]"
  return
fi

sudo docker run -d -p 8888:52848 -e dp_ini=config.prod.ini -v "$(dirname $(dirname $(pwd)))/dp_tornado/engine/template/bbs:/data/app" dp4p:$dpver-$pyver
